apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghdfhrqhtmmm-springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ghdfhrqhtmmm-springboot
  template:
    metadata:
      labels:
        app: ghdfhrqhtmmm-springboot
    spec:
      containers:
        - name: springboot
          image: ghdfhrqhtmmm/ghdfhrqhtmmm/webtest1.0
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: ghdfhrqhtmmm-springboot
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: ghdfhrqhtmmm-springboot
