apiVersion: apps/v1
kind: Deployment
metadata:
  name: template
  labels:
    app:
spec:
  replicas: 1
  selector:
    matchLabels:
  template:
    metadata:
      labels:
    spec:
      containers:
      - name: template
        image: ghdfhrqhtmmm/webtest1.0
      ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
